# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    types: [ opened, synchronize ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:
    name: Lint    
    runs-on: node:15.10.0-alpine
    steps:
      - name: Install dependencies
        run: yarn install

      - name: Run linters
        run: |
          yarn prettier --ignore-path .gitignore --loglevel warn "**/*.{js,ts,css,md,json}"
          yarn eslint . --ignore-path .gitignore
